name: fastapi_ddd_template
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_ADMIN}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_admin_secret
      POSTGRES_DB: ${DB_PATH}
    ports:
      - "5432:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
    - source: db_admin_secret
      target: db_admin_secret
  db-bootstrap:
    image: postgres:16
    depends_on:
      db:
        condition: service_healthy
    restart: 'no'
    entrypoint:
    - /bin/bash
    - -lc
    - bash /bootstrap/bootstrap_db.sh
    environment:
      DB_HOST: db
      DB_ADMIN: ${DB_ADMIN}
      DB_ADMIN_PWD_FILE: /run/secrets/db_admin_secret
      DB_PATH: ${DB_PATH}
      DB_USER: ${DB_USER}
      DB_USER_PWD_FILE: /run/secrets/db_user_secret
      DB_TABLE_SCHEMA: ${DB_TABLE_SCHEMA}
    secrets:
    - source: db_admin_secret
      target: db_admin_secret
    - source: db_user_secret
      target: db_user_secret
    volumes:
    - ../deploy/bootstrap:/bootstrap:ro
  api:
    image: fastapi_ddd_template_api:dev
    depends_on:
      db:
        condition: service_healthy
      db-bootstrap:
        condition: service_completed_successfully
    environment:
      FASTAPI_DDD_TEMPLATE_ENV: ${FASTAPI_DDD_TEMPLATE_ENV}
      FASTAPI_DDD_TEMPLATE_DEBUG: ${FASTAPI_DDD_TEMPLATE_DEBUG}
      FASTAPI_DDD_TEMPLATE_JWT_ALGORITHM: ${FASTAPI_DDD_TEMPLATE_JWT_ALGORITHM}
      FASTAPI_DDD_TEMPLATE_JWT_TOKEN_EXPIRY_TIME: ${FASTAPI_DDD_TEMPLATE_JWT_TOKEN_EXPIRY_TIME}
      DB_DRIVER: ${DB_DRIVER}
      DB_USER: ${DB_USER}
      DB_PATH: ${DB_PATH}
      DB_HOST: ${DB_HOST}
      DB_TABLE_SCHEMA: ${DB_TABLE_SCHEMA}
      FASTAPI_DDD_TEMPLATE_BOOTSTRAP_FLAG: ${FASTAPI_DDD_TEMPLATE_BOOTSTRAP_FLAG}
      FASTAPI_DDD_TEMPLATE_BOOTSTRAP_ADMIN: ${FASTAPI_DDD_TEMPLATE_BOOTSTRAP_ADMIN}
    ports:
    - 127.0.0.1:8000:8000
    restart: unless-stopped
    entrypoint:
    - python
    - ./entrypoint.py
    - uvicorn
    - app.interface.http.main:app
    - --host
    - 0.0.0.0
    - --port
    - "8000"
    secrets:
    - source: fastapi_ddd_template_jwt_secret
      target: fastapi_ddd_template_jwt_secret
    - source: db_user_secret
      target: db_user_secret
    - source: fastapi_ddd_template_bootstrap_admin_password_hash
      target: fastapi_ddd_template_bootstrap_admin_password_hash
volumes:
  pgdata: {}
secrets:
  db_admin_secret:
    file: ./secrets/db_admin_secret
  fastapi_ddd_template_bootstrap_admin_password_hash:
    file: ./secrets/fastapi_ddd_template_bootstrap_admin_password_hash
  fastapi_ddd_template_jwt_secret:
    file: ./secrets/fastapi_ddd_template_jwt_secret
  db_user_secret:
    file: ./secrets/db_user_secret
