nameOverride: ""
fullnameOverride: ""

image:
  repository: ""
  tag: ""
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []

config:
  enabled: true
  data:
    FASTAPI_DDD_TEMPLATE_ENV: ""
    FASTAPI_DDD_TEMPLATE_DEBUG: ""
    FASTAPI_DDD_TEMPLATE_JWT_ALGORITHM: "HS256"
    FASTAPI_DDD_TEMPLATE_JWT_TOKEN_EXPIRY_TIME: "30"
    DB_ADMIN: "postgres"
    DB_USER: ""
    DB_PATH: ""
    DB_DRIVER: "postgresql+asyncpg"
    DB_TABLE_SCHEMA: "fastapi_ddd_template"
    FASTAPI_DDD_TEMPLATE_BOOTSTRAP_FLAG: "true"
    FASTAPI_DDD_TEMPLATE_BOOTSTRAP_ADMIN: "admin"

secrets:
  existingName: "fastapi-ddd-template-secrets"

api:
  version: ""
  replicaCount: 1
  containerPort: 8000
  service:
    type: ClusterIP
    port: 80
  probes:
    enabled: true
    path: /health
    readiness: { initialDelaySeconds: 15, periodSeconds: 20 }
    liveness:  { initialDelaySeconds: 20, periodSeconds: 20 }
  resources:
    requests: { cpu: "50m",  memory: "64Mi" }
    limits:   { cpu: "250m", memory: "256Mi" }

  envFromConfigKeys:
    - FASTAPI_DDD_TEMPLATE_ENV
    - FASTAPI_DDD_TEMPLATE_DEBUG
    - FASTAPI_DDD_TEMPLATE_JWT_ALGORITHM
    - FASTAPI_DDD_TEMPLATE_JWT_TOKEN_EXPIRY_TIME
    - DB_DRIVER
    - DB_HOST
    - DB_PATH
    - DB_USER
    - DB_TABLE_SCHEMA
    - FASTAPI_DDD_TEMPLATE_BOOTSTRAP_FLAG
    - FASTAPI_DDD_TEMPLATE_BOOTSTRAP_ADMIN

  secretFilesPath:
    FASTAPI_DDD_TEMPLATE_JWT_SECRET_PATH: fastapi_ddd_template_jwt_secret
    BOOTSTRAP_ADMIN_PASSWORD_HASH_PATH: fastapi_ddd_template_bootstrap_admin_password_hash
    DB_USER_SECRET_PATH: db_user_secret

db:
  image: { repository: postgres, tag: "16", pullPolicy: IfNotPresent }
  port: 5432
  persistence:
    enabled: false
    size: 1Gi
    storageClassName: ""
  resources:
    requests: { cpu: "100m", memory: "256Mi" }
    limits:   { cpu: "1",    memory: "1Gi" }

  envFromConfigKeys:
    - DB_ADMIN
    - DB_PATH

  adminSecretPath: db_admin_secret

dbBootstrap:
  enabled: true
  image: { repository: postgres, tag: "16", pullPolicy: IfNotPresent }
  backoffLimit: 3
  resources:
    requests: { cpu: "50m",  memory: "64Mi" }
    limits:   { cpu: "250m", memory: "256Mi" }

  envFromConfigKeys:
    - DB_ADMIN
    - DB_USER
    - DB_PATH
    - DB_HOST
    - DB_TABLE_SCHEMA

  adminSecretFilePath: db_admin_secret
  userSecretFilePath:  db_user_secret

  script: ""
