image:
  repository: ""
  tag: ""
  digest: ""

config:
  enabled: true
  data:
    FASTAPI_DDD_TEMPLATE_ENV: "test"
    FASTAPI_DDD_TEMPLATE_DEBUG: "false"

    DB_USER: "ci_db_user"
    DB_PATH: "fastapi_ddd_template_ci_db"

api:
  replicaCount: 1

db:
  persistence:
    enabled: false

dbBootstrap:
  enabled: true
