name: _fast checks

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version to use"
        required: true
        type: string

jobs:
  fast-check:
    runs-on: ubuntu-latest
    env:
      ENV_FILE: ci/env.test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-2.2.1-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-2.2.1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry==2.2.1
          poetry install
      - name: Lint & Static Analysis
        run: make lint
      - name: Run Unit Tests
        run: poetry run make test-unit
