name: CI pull request

on:
  pull_request:
    branches:
      - develop
      - release/**
      - hotfix/**
      - main
  workflow_dispatch: {}

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-fast-checks:
    uses: ./.github/workflows/_fast-checks.yml
    with:
      python-version: "3.12"
  
  build-and-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Docker images
        run: make build
      - name: Run Integration Tests
        run: make test-int